# Generated by Django 3.2.1 on 2021-05-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "city_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("living_cost", models.DecimalField(decimal_places=6, max_digits=15)),
                ("safety", models.DecimalField(decimal_places=6, max_digits=15)),
                ("population", models.IntegerField()),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=15)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=15)),
                ("teleport_url", models.TextField()),
                ("city_summary", models.TextField()),
                ("img_url", models.TextField()),
                ("wx_jan", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_feb", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_mar", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_apr", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_may", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_jun", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_jul", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_aug", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_sep", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_oct", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_nov", models.DecimalField(decimal_places=6, max_digits=15)),
                ("wx_dec", models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
    ]
